syntax = "proto3";

option csharp_namespace = "DrakkarVpn.Agent.Infrastructure.Grpc.Protos";

package v2ray;

service V2RayTune {
  rpc RegisterPeer (RegisterPeerRequest) returns (RegisterPeerResponse);
  rpc RevokePeer   (RevokePeerRequest)   returns (RevokePeerResponse);
}

message RegisterPeerRequest {
  string user_id = 1;   
}

message RegisterPeerResponse {
  string peer_uuid = 1; 
  string config_raw = 2;
}

message RevokePeerRequest {
  string peer_uuid = 1; 
}

message RevokePeerResponse {
  bool success = 1;
}
