global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'core-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          service: 'core'

  - job_name: 'agent'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5001']
        labels:
          service: 'agent'

