using DrakkarVpn.Core.Api.Extensions;
using DrakkarVpn.Core.Api.Middlewares;
using DrakkarVpn.Core.Api.Modules.Idempotency.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Orchestrator.Infrastructure.BackgroundWorkers;
using DrakkarVpn.Core.Api.Modules.Orchestrator.Infrastructure.Extensions;
using DrakkarVpn.Core.Api.Modules.Peers.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Servers.Application;
using DrakkarVpn.Core.Api.Modules.Servers.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Subscriptions.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Tariffs.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Users.Application;
using DrakkarVpn.Core.Api.Modules.Users.Infrastructure;

var builder = WebApplication.CreateBuilder(args);
var services = builder.Services;
var configuration = builder.Configuration;

services.AddApiBasics();
services.AddCoreApplication(
    typeof(UsersApplicationMarker).Assembly,
    typeof(ServerApplicationMarker).Assembly);

services.AddCoreInfrastructure(configuration.GetConnectionString("Default"));
services.AddUsersInfrastructure();
services.AddServersInfrastructure();
services.AddPeersInfrastructure();
services.AddAgentInfrastructure();
services.AddTariffsInfrastructure();
services.AddSubscriptionsInfrastructure();
services.AddIdempotencyInfrastructure();
services.AddHostedService<ServerHealthBackgroundWorker>();
services.AddHostedService<SubscriptionExpirationWorker>();
services.AddHttpClient();
services.AddAutoGeneratedLinks(configuration);


services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy
            .SetIsOriginAllowed(origin => new Uri(origin).Host == "localhost")
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials();
    });
});



var app = builder.Build();
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseCors("AllowFrontend");
app.UseExceptionHandling();
app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();
app.Run();