using DrakkarVpn.Core.Api.Extensions;
using DrakkarVpn.Core.Api.Middlewares;
using DrakkarVpn.Core.Api.Modules.Idempotency.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Orchestrator.Infrastructure.BackgroundWorkers;
using DrakkarVpn.Core.Api.Modules.Orchestrator.Infrastructure.Extensions;
using DrakkarVpn.Core.Api.Modules.Peers.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Servers.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Subscriptions.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Tariffs.Infrastructure;
using DrakkarVpn.Core.Api.Modules.Users.Infrastructure;
using Microsoft.OpenApi.Models;
using Prometheus;
using Serilog;

var builder = WebApplication.CreateBuilder(args);
var services = builder.Services;
var configuration = builder.Configuration;

services.AddDrakkarMediatR(); //тут пока приостановили идемпотентность из конфилкта пайплайнов
services.AddApiBasics();
services.AddCoreInfrastructure(configuration.GetConnectionString("Default"));
services.AddUsersInfrastructure(configuration);
services.AddServersInfrastructure();
services.AddPeersInfrastructure();
services.AddAgentInfrastructure();
services.AddTariffsInfrastructure();
services.AddSubscriptionsInfrastructure();
services.AddIdempotencyInfrastructure();
services.AddHostedService<ServerHealthBackgroundWorker>();
services.AddHostedService<PeerMetricsBackgroundWorker>();
services.AddHostedService<SubscriptionExpirationWorker>();
services.AddHttpClient();
services.AddAutoGeneratedLinks(configuration);

configuration.AddJsonFile("appsettings.Serilog.json", optional: false, reloadOnChange: true);
builder.Host.UseSerilog((ctx, lc) => lc
    .ReadFrom.Configuration(ctx.Configuration)
    .Enrich.FromLogContext()
    .Enrich.WithProperty("Service", "Drakkar.Core")
);

services.AddCors(options =>
{
    options.AddPolicy("AllowFrontend", policy =>
    {
        policy
            .SetIsOriginAllowed(origin => new Uri(origin).Host == "localhost")
            .AllowAnyHeader()
            .AllowAnyMethod()
            .AllowCredentials();
    });
});

services.AddSwaggerGen(c =>
{
    var bearerScheme = new OpenApiSecurityScheme
    {
        Name = "Authorization",
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        In = ParameterLocation.Header,
        Description = "Enter 'Bearer {token}'"
    };

    c.AddSecurityDefinition("Bearer", bearerScheme);

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
            },
            Array.Empty<string>()
        }
    });
});

var app = builder.Build();
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseRouting();               
app.UseCors("AllowFrontend");    
app.UseAuthentication(); 
app.UseAuthorization();       
app.UseExceptionHandling();     

app.MapControllers();          
app.MapMetrics();                

app.Run();