<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
        <PackageReference Include="Grpc.Tools" Version="2.72.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.19"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="API\" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Infrastructure/gRpc/Protos/**/*.proto"
                  GrpcServices="Client"
                  ProtoRoot="Infrastructure/gRpc/Protos" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.27.2" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\DrakkarVpn.Shared\DrakkarVpn.Shared.csproj" />
    </ItemGroup>



</Project>
