// <auto-generated />
using System;
using DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.EF;
using DrakkarVpn.Servers.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrakkarVpn.Servers.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260416130406_AddProfileAndIncident")]
    partial class AddProfileAndIncident
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("servers")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentBaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_base_url");

                    b.Property<string>("AgentTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_token_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MaxPeers")
                        .HasColumnType("integer")
                        .HasColumnName("max_peers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicHost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_host");

                    b.Property<int>("PublicPort")
                        .HasColumnType("integer")
                        .HasColumnName("public_port");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Region", "Status")
                        .HasDatabaseName("ix_servers_region_status");

                    b.ToTable("servers", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerMetricsHistory", b =>
                {
                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<decimal>("InfraLatencyMs")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("infra_latency_ms");

                    b.Property<bool>("Reachable")
                        .HasColumnType("boolean")
                        .HasColumnName("reachable");

                    b.Property<long>("TrafficRxDeltaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_rx_delta_bytes");

                    b.Property<long>("TrafficTxDeltaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_tx_delta_bytes");

                    b.Property<decimal>("VpnSpeedMbps")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("vpn_speed_mbps");

                    b.HasKey("PeriodStartUtc", "ServerId");

                    b.HasIndex("ServerId", "PeriodStartUtc")
                        .HasDatabaseName("ix_server_metrics_server_ts");

                    b.ToTable("server_metrics_history", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerPollState", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BackoffUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastDeltaAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastKnownPeersActive")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLeaseRenewedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPollErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastPollFinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastPollLatencyMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastPollStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("LastPollSuccess")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReachableUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastRxDelta")
                        .HasColumnType("bigint");

                    b.Property<long>("LastRxTotal")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastTotalsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastTxDelta")
                        .HasColumnType("bigint");

                    b.Property<long>("LastTxTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdaterInstance")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServerId");

                    b.HasIndex("BackoffUntilUtc");

                    b.HasIndex("LastReachableUtc");

                    b.HasIndex("LeaseUntilUtc");

                    b.ToTable("server_poll_states", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerRealtimeStats", b =>
                {
                    b.Property<Guid>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("OnlinePeers")
                        .HasColumnType("integer")
                        .HasColumnName("online_peers");

                    b.Property<DateTime?>("TrafficCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("traffic_calculated_at_utc");

                    b.Property<long>("TrafficLast1hBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_last_1h_bytes");

                    b.Property<long>("TrafficLast24hBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_last_24h_bytes");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ServerId");

                    b.ToTable("server_realtime_stats", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Servers.Domain.Aggregates.ServerTransportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("activated_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("GrpcAuthority")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("grpc_authority");

                    b.Property<string>("GrpcServiceName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("grpc_service_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("RealityDest")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reality_dest");

                    b.Property<string>("RealityFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("reality_fingerprint");

                    b.Property<string>("RealityPublicKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reality_public_key");

                    b.Property<string>("RealityShortId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reality_short_id");

                    b.Property<string>("RealitySni")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reality_sni");

                    b.Property<int>("SecurityType")
                        .HasColumnType("integer")
                        .HasColumnName("security_type");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TransportType")
                        .HasColumnType("integer")
                        .HasColumnName("transport_type");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ServerId")
                        .IsUnique()
                        .HasDatabaseName("ux_server_transport_profiles_one_active_per_server")
                        .HasFilter("status = 2");

                    b.HasIndex("ServerId", "Priority")
                        .HasDatabaseName("ix_server_transport_profiles_server_id_priority");

                    b.ToTable("server_transport_profiles", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Servers.Domain.Aggregates.TransportIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActiveProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedProbeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EscalatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedProbeCount")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Reason")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RemediationFinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RemediationStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuccessfulProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("TriggeredBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("Status");

                    b.HasIndex("ServerId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (1,2,3)");

                    b.ToTable("transport_incidents", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Servers.Domain.Aggregates.TransportRemediationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("IncidentId", "ProfileId")
                        .IsUnique();

                    b.ToTable("transport_incident_attempts", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", b =>
                {
                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.BenchmarkSnapshot", "Benchmark", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<double>("MaxSpeedMbps")
                                .HasColumnType("double precision")
                                .HasColumnName("benchmark_max_speed_mbps");

                            b1.Property<DateTime>("MeasuredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("benchmark_measured_at");

                            b1.HasKey("ServerId");

                            b1.ToTable("servers", "servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.HealthSnapshot", "Health", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("LastHealthAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("health_updated_at");

                            b1.Property<int>("PeersActive")
                                .HasColumnType("integer")
                                .HasColumnName("health_peers_active");

                            b1.Property<bool>("Reachable")
                                .HasColumnType("boolean")
                                .HasColumnName("health_reachable");

                            b1.HasKey("ServerId");

                            b1.HasIndex("Reachable")
                                .HasDatabaseName("ix_servers_health_reachable");

                            b1.ToTable("servers", "servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.MetricsSnapshot", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<double>("InfraLatencyMs")
                                .HasColumnType("double precision")
                                .HasColumnName("metrics_infra_latency_ms");

                            b1.Property<DateTime>("LastMetricsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("metrics_updated_at");

                            b1.Property<long>("TrafficRxBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_rx_bytes");

                            b1.Property<long>("TrafficTxBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_tx_bytes");

                            b1.Property<double>("VpnSpeedMbps")
                                .HasColumnType("double precision")
                                .HasColumnName("metrics_vpn_speed_mbps");

                            b1.HasKey("ServerId");

                            b1.ToTable("servers", "servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.Navigation("Benchmark")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerPollState", b =>
                {
                    b.HasOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", null)
                        .WithOne()
                        .HasForeignKey("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerPollState", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrakkarVpn.Servers.Domain.Aggregates.ServerTransportProfile", b =>
                {
                    b.HasOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", null)
                        .WithMany("_transportProfiles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrakkarVpn.Servers.Domain.Aggregates.TransportRemediationAttempt", b =>
                {
                    b.HasOne("DrakkarVpn.Servers.Domain.Aggregates.TransportIncident", null)
                        .WithMany("Attempts")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", b =>
                {
                    b.Navigation("_transportProfiles");
                });

            modelBuilder.Entity("DrakkarVpn.Servers.Domain.Aggregates.TransportIncident", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
