// <auto-generated />
using System;
using DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.EF;
using DrakkarVpn.Servers.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrakkarVpn.Servers.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260327134314_AddFieldsOnDomain")]
    partial class AddFieldsOnDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("servers")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentBaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_base_url");

                    b.Property<string>("AgentTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_token_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MaxPeers")
                        .HasColumnType("integer")
                        .HasColumnName("max_peers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicHost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_host");

                    b.Property<int>("PublicPort")
                        .HasColumnType("integer")
                        .HasColumnName("public_port");

                    b.Property<string>("RealityPublicKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reality_public_key");

                    b.Property<string>("RealityShortId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reality_short_id");

                    b.Property<string>("RealitySni")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reality_sni");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Region", "Status")
                        .HasDatabaseName("ix_servers_region_status");

                    b.ToTable("servers", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerMetricsHistory", b =>
                {
                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<decimal>("InfraLatencyMs")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("infra_latency_ms");

                    b.Property<bool>("Reachable")
                        .HasColumnType("boolean")
                        .HasColumnName("reachable");

                    b.Property<long>("TrafficRxDeltaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_rx_delta_bytes");

                    b.Property<long>("TrafficTxDeltaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_tx_delta_bytes");

                    b.Property<decimal>("VpnSpeedMbps")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("vpn_speed_mbps");

                    b.HasKey("PeriodStartUtc", "ServerId");

                    b.HasIndex("ServerId", "PeriodStartUtc")
                        .HasDatabaseName("ix_server_metrics_server_ts");

                    b.ToTable("server_metrics_history", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerPollState", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BackoffUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastDeltaAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastKnownPeersActive")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLeaseRenewedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPollErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastPollFinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastPollLatencyMs")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastPollStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("LastPollSuccess")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastReachableUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastRxDelta")
                        .HasColumnType("bigint");

                    b.Property<long>("LastRxTotal")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastTotalsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastTxDelta")
                        .HasColumnType("bigint");

                    b.Property<long>("LastTxTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdaterInstance")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ServerId");

                    b.HasIndex("BackoffUntilUtc");

                    b.HasIndex("LastReachableUtc");

                    b.HasIndex("LeaseUntilUtc");

                    b.ToTable("server_poll_states", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerRealtimeStats", b =>
                {
                    b.Property<Guid>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("OnlinePeers")
                        .HasColumnType("integer")
                        .HasColumnName("online_peers");

                    b.Property<DateTime?>("TrafficCalculatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("traffic_calculated_at_utc");

                    b.Property<long>("TrafficLast1hBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_last_1h_bytes");

                    b.Property<long>("TrafficLast24hBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_last_24h_bytes");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ServerId");

                    b.ToTable("server_realtime_stats", "servers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", b =>
                {
                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.BenchmarkSnapshot", "Benchmark", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<double>("MaxSpeedMbps")
                                .HasColumnType("double precision")
                                .HasColumnName("benchmark_max_speed_mbps");

                            b1.Property<DateTime>("MeasuredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("benchmark_measured_at");

                            b1.HasKey("ServerId");

                            b1.ToTable("servers", "servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.HealthSnapshot", "Health", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("LastHealthAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("health_updated_at");

                            b1.Property<int>("PeersActive")
                                .HasColumnType("integer")
                                .HasColumnName("health_peers_active");

                            b1.Property<bool>("Reachable")
                                .HasColumnType("boolean")
                                .HasColumnName("health_reachable");

                            b1.HasKey("ServerId");

                            b1.HasIndex("Reachable")
                                .HasDatabaseName("ix_servers_health_reachable");

                            b1.ToTable("servers", "servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.MetricsSnapshot", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<double>("InfraLatencyMs")
                                .HasColumnType("double precision")
                                .HasColumnName("metrics_infra_latency_ms");

                            b1.Property<DateTime>("LastMetricsAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("metrics_updated_at");

                            b1.Property<long>("TrafficRxBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_rx_bytes");

                            b1.Property<long>("TrafficTxBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_tx_bytes");

                            b1.Property<double>("VpnSpeedMbps")
                                .HasColumnType("double precision")
                                .HasColumnName("metrics_vpn_speed_mbps");

                            b1.HasKey("ServerId");

                            b1.ToTable("servers", "servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.Navigation("Benchmark")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("Metrics")
                        .IsRequired();
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerPollState", b =>
                {
                    b.HasOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", null)
                        .WithOne()
                        .HasForeignKey("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerPollState", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
