// <auto-generated />
using System;
using DrakkarVpn.Core.Api.Modules.Subscriptions.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrakkarVpn.Subscriptions.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    [Migration("20260309185452_AddScheme")]
    partial class AddScheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("subscriptions")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Subscriptions.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<int>("MaxDevices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("max_devices");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("StatusUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscriptions_user_active")
                        .HasFilter("\"status\" = 1");

                    b.HasIndex("Status", "StatusUpdatedAtUtc", "Id")
                        .HasDatabaseName("ix_subs_status_statusupdatedat_id");

                    b.HasIndex("UserId", "Status", "EndAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_subscriptions_user_status_endat_desc");

                    b.ToTable("subscriptions", "subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
