name: drakkar-node

services:
  xray:
    dns:
    - 9.9.9.9    
    - 149.112.112.112
    image: ghcr.io/xtls/xray-core:latest
    container_name: drakkar-xray
    restart: unless-stopped
    ports:
      - "1443:1443/tcp"
      - "127.0.0.1:10086:10086/tcp"
    volumes:
      - ../configs/xray/config.prod.json:/etc/xray/config.json:ro
      - xray-logs:/var/log/xray
    command: ["run", "-c", "/etc/xray/config.json"]
    networks:
      - drakkar-node-net

  agent:
    image: ${AGENT_IMAGE}:${AGENT_TAG}
    container_name: drakkar-agent
    restart: unless-stopped
    depends_on:
      - xray
    env_file:
      - ../env/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:5046
    ports:
      - "${AGENT_HOST_BIND:-127.0.0.1}:5046:5046"
    networks:
      - drakkar-node-net

networks:
  drakkar-node-net:
    driver: bridge

volumes:
  xray-logs: