// <auto-generated />
using System;
using DrakkarVpn.Core.Api.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrakkarVpn.Core.Api.Infrastructure.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Idempotency.Domain.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ActorKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorKey", "Action", "RequestId")
                        .IsUnique();

                    b.ToTable("IdempotencyKeys", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Domain.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentPeerUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_peer_uuid");

                    b.Property<string>("ConfigRaw")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_raw");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("LastHandshakeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_handshake_at");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AgentPeerUuid")
                        .IsUnique()
                        .HasDatabaseName("ux_peers_agent_peer_uuid");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_peers_server_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_peers_user_id");

                    b.HasIndex("SubscriptionId", "DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_peers_sub_device_active")
                        .HasFilter("\"status\" = 0");

                    b.HasIndex("SubscriptionId", "Status")
                        .HasDatabaseName("ix_peers_sub_status");

                    b.ToTable("peers", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentBaseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_base_url");

                    b.Property<string>("AgentTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("agent_token_encrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MaxPeers")
                        .HasColumnType("integer")
                        .HasColumnName("max_peers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PublicHost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_host");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Region")
                        .HasDatabaseName("ix_servers_region");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_servers_status");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Infrastructure.Entities.ServerMetricsHistory", b =>
                {
                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<decimal>("InfraLatencyMs")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("infra_latency_ms");

                    b.Property<int?>("MaxPeers")
                        .HasColumnType("integer")
                        .HasColumnName("max_peers");

                    b.Property<int>("PeersActive")
                        .HasColumnType("integer")
                        .HasColumnName("peers_active");

                    b.Property<bool>("Reachable")
                        .HasColumnType("boolean")
                        .HasColumnName("reachable");

                    b.Property<long>("TrafficRxBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_rx_bytes");

                    b.Property<long>("TrafficTxBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_tx_bytes");

                    b.Property<decimal>("VpnSpeedMbps")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("vpn_speed_mbps");

                    b.HasKey("PeriodStartUtc", "ServerId");

                    b.ToTable("server_metrics_history", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Subscriptions.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxDevices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Tariffs.Domain.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("tariffs", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Users.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.HasKey("Id");

                    b.HasIndex("TelegramId")
                        .IsUnique();

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Users.Domain.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_user");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Servers.Domain.Server", b =>
                {
                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.BenchmarkSnapshot", "Benchmark", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<double>("MaxSpeedMbps")
                                .HasColumnType("double precision")
                                .HasColumnName("benchmark_max_speed_mbps");

                            b1.Property<DateTime>("MeasuredAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("benchmark_measured_at");

                            b1.HasKey("ServerId");

                            b1.ToTable("servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.HealthSnapshot", "Health", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PeersActive")
                                .HasColumnType("integer")
                                .HasColumnName("health_peers_active");

                            b1.Property<bool>("Reachable")
                                .HasColumnType("boolean")
                                .HasColumnName("health_reachable");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("health_updated_at");

                            b1.HasKey("ServerId");

                            b1.HasIndex("Reachable")
                                .HasDatabaseName("ix_servers_health_reachable");

                            b1.ToTable("servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("DrakkarVpn.Core.Api.Modules.Servers.Domain.VO.MetricsSnapshot", "Metrics", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uuid");

                            b1.Property<double>("InfraLatencyMs")
                                .HasColumnType("double precision")
                                .HasColumnName("metrics_infra_latency_ms");

                            b1.Property<long>("TrafficRxBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_rx_bytes");

                            b1.Property<long>("TrafficTxBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("metrics_tx_bytes");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("metrics_updated_at");

                            b1.Property<double>("VpnSpeedMbps")
                                .HasColumnType("double precision")
                                .HasColumnName("metrics_vpn_speed_mbps");

                            b1.HasKey("ServerId");

                            b1.ToTable("servers");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.Navigation("Benchmark")
                        .IsRequired();

                    b.Navigation("Health")
                        .IsRequired();

                    b.Navigation("Metrics")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
