// <auto-generated />
using System;
using DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrakkarVpn.Peers.Migrations
{
    [DbContext(typeof(PeerDbContext))]
    [Migration("20260331163954_AddUpdateConfig")]
    partial class AddUpdateConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("peers")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Domain.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AgentPeerUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("agent_peer_uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_online");

                    b.Property<DateTime?>("LastDataAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_data_at");

                    b.Property<DateTime?>("LastLatencyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_latency_at");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<double?>("SpeedMbps")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("speed_mbps");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("StatusUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at_utc");

                    b.Property<long>("TotalRxBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_rx_bytes");

                    b.Property<long>("TotalTxBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_tx_bytes");

                    b.Property<double?>("VpnLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("vpn_latency_ms");

                    b.HasKey("Id");

                    b.HasIndex("AgentPeerUuid")
                        .IsUnique()
                        .HasDatabaseName("ux_peers_agent_peer_uuid");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_peers_device_active")
                        .HasFilter("\"status\" = 0");

                    b.HasIndex("ServerId")
                        .HasDatabaseName("ix_peers_server_id");

                    b.HasIndex("StatusUpdatedAtUtc")
                        .HasDatabaseName("ix_peers_statusupdatedat");

                    b.HasIndex("ServerId", "IsOnline")
                        .HasDatabaseName("ix_peers_server_online")
                        .HasFilter("\"is_online\" = TRUE");

                    b.HasIndex("ServerId", "LastDataAt")
                        .HasDatabaseName("ix_peers_server_lastdata")
                        .HasFilter("\"last_data_at\" IS NOT NULL");

                    b.HasIndex("ServerId", "Status")
                        .HasDatabaseName("ix_peers_server_status");

                    b.HasIndex("Status", "StatusUpdatedAtUtc")
                        .HasDatabaseName("ix_peers_status_statusupdatedat");

                    b.ToTable("peers", "peers", t =>
                        {
                            t.HasCheckConstraint("ck_peers_total_rx_bytes_nonneg", "total_rx_bytes >= 0");

                            t.HasCheckConstraint("ck_peers_total_tx_bytes_nonneg", "total_tx_bytes >= 0");

                            t.HasCheckConstraint("ck_peers_vpn_latency_ms_valid", "vpn_latency_ms IS NULL OR vpn_latency_ms >= 0");
                        });
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.Entities.DeviceReadRow", b =>
                {
                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable("devices", "users", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.Entities.PeerMetricsHistory", b =>
                {
                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("period_start");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("server_id");

                    b.Property<Guid>("PeerId")
                        .HasColumnType("uuid")
                        .HasColumnName("peer_id");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<long>("RxDeltaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("rx_delta_bytes");

                    b.Property<double?>("SpeedMbps")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("speed_mbps");

                    b.Property<long>("TotalRxBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_rx_bytes");

                    b.Property<long>("TotalTxBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("total_tx_bytes");

                    b.Property<long>("TxDeltaBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tx_delta_bytes");

                    b.Property<double?>("VpnLatencyMs")
                        .HasColumnType("double precision")
                        .HasColumnName("vpn_latency_ms");

                    b.HasKey("PeriodStartUtc", "ServerId", "PeerId");

                    b.HasIndex("PeriodStartUtc");

                    b.HasIndex("PeerId", "PeriodStartUtc");

                    b.HasIndex("ServerId", "PeriodStartUtc", "IsOnline")
                        .HasDatabaseName("ix_peer_hist_srv_period_online");

                    b.HasIndex("ServerId", "PeriodStartUtc", "PeerId")
                        .HasDatabaseName("ix_peer_metrics_server_period_peer");

                    b.ToTable("peer_metrics_history", "peers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.Entities.PeerProvisionJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("JobId");

                    b.Property<DateTime?>("AgentAppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AgentPeerUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("AgentPeerUuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("Attempt");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("DeviceId");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("LastErrorCode");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("LastErrorMessage");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("LeaseOwner");

                    b.Property<DateTime?>("LeaseUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LeaseUntilUtc");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("MaxAttempts");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("NextAttemptAtUtc");

                    b.Property<Guid?>("PeerId")
                        .HasColumnType("uuid")
                        .HasColumnName("PeerId");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid")
                        .HasColumnName("ServerId");

                    b.Property<short>("State")
                        .HasColumnType("smallint")
                        .HasColumnName("State");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAtUtc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("UserId");

                    b.HasKey("JobId");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("ux_peer_provision_jobs_device_active")
                        .HasFilter("\"State\" <> 3");

                    b.HasIndex("PeerId", "AgentAppliedAtUtc");

                    b.HasIndex("State", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_peer_provision_jobs_state_next");

                    b.ToTable("peer_provision_jobs", "peers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.Entities.PeerSyncIssueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentPeerUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PeerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "Type", "DetectedAtUtc");

                    b.ToTable("peer_sync_issues", "peers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.Entities.PeerTrafficAgg", b =>
                {
                    b.Property<Guid>("PeerId")
                        .HasColumnType("uuid");

                    b.Property<long>("Last1hBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("Last24hBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PeerId");

                    b.HasIndex("Last1hBytes");

                    b.HasIndex("Last24hBytes");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("peer_traffic_agg", "peers");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.Entities.PeerTrafficAgg", b =>
                {
                    b.HasOne("DrakkarVpn.Core.Api.Modules.Peers.Domain.Peer", "Peer")
                        .WithOne()
                        .HasForeignKey("DrakkarVpn.Core.Api.Modules.Peers.Infrastructure.Entities.PeerTrafficAgg", "PeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peer");
                });
#pragma warning restore 612, 618
        }
    }
}
