<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions"/>
        <PackageReference Include="MediatR"/>
    </ItemGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\modules\DrakkarVpn.Observability\DrakkarVpn.Observability.csproj" />
        <ProjectReference Include="..\..\modules\DrakkarVpn.Peers\DrakkarVpn.Peers.csproj" />
        <ProjectReference Include="..\..\modules\DrakkarVpn.Servers\DrakkarVpn.Servers.csproj" />
        <ProjectReference Include="..\..\modules\DrakkarVpn.Subscriptions\DrakkarVpn.Subscriptions.csproj" />
        <ProjectReference Include="..\..\modules\DrakkarVpn.Tariffs\DrakkarVpn.Tariffs.csproj" />
        <ProjectReference Include="..\..\modules\DrakkarVpn.Users\DrakkarVpn.Users.csproj" />
        <ProjectReference Include="..\DrakkarVpn.Shared\DrakkarVpn.Shared.csproj" />
    </ItemGroup>

</Project>