using System.Text.Json.Serialization;
using DrakkarVpn.Core.Api.Modules.Orchestrator.Application.Options;
using Microsoft.OpenApi.Models;

namespace DrakkarVpn.Core.Api.Extensions;

public static class HostServiceCollectionExtensions
{
    public static IServiceCollection AddUserHostApi(this IServiceCollection services)
    {
        services.AddControllers()
            .AddJsonOptions(o => o.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter()));

        services.AddEndpointsApiExplorer();
        services.AddSwaggerGen(c =>
            c.SwaggerDoc("v1", new OpenApiInfo { Title = "Drakkar User API", Version = "v1" }));

        return services;
    }

    public static IServiceCollection AddLocalCorsForFrontend(this IServiceCollection services)
    {
        services.AddCors(options =>
        {
            options.AddPolicy("AllowFrontend", policy =>
            {
                policy
                    .SetIsOriginAllowed(origin => new Uri(origin).Host == "localhost")
                    .AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials();
            });
        });

        return services;
    }

    public static IServiceCollection AddSwaggerJwt(this IServiceCollection services)
    {
        services.AddSwaggerGen(c =>
        {
            var bearerScheme = new OpenApiSecurityScheme
            {
                Name = "Authorization",
                Type = SecuritySchemeType.Http,
                Scheme = "bearer",
                BearerFormat = "JWT",
                In = ParameterLocation.Header,
                Description = "Enter 'Bearer {token}'"
            };

            c.AddSecurityDefinition("Bearer", bearerScheme);

            c.AddSecurityRequirement(new OpenApiSecurityRequirement
            {
                {
                    new OpenApiSecurityScheme
                    {
                        Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "Bearer" }
                    },
                    Array.Empty<string>()
                }
            });
        });

        return services;
    }
    
    public static IServiceCollection AddAutoGeneratedLinks(this IServiceCollection services, IConfiguration configuration)
    {
        services.Configure<VpnLinkOptions>(configuration.GetSection("VpnLink"));
        return services;
    }
}