using DrakkarVpn.Idempotency;
using DrakkarVpn.Observability;
using DrakkarVpn.Peers;
using DrakkarVpn.Servers;
using DrakkarVpn.Shared.InstanceProvider;
using DrakkarVpn.Subscriptions;
using DrakkarVpn.Tariffs;
using DrakkarVpn.Users;
using Idempotency;

namespace DrakkarVpn.Core.Api.Extensions;

public static class UserHostCompositionExtensions
{
    public static IServiceCollection AddUserHostComposition(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        // shared infra
        services.AddHttpClient();
        services.AddAutoGeneratedLinks(configuration);
        services.AddRedis(configuration);
        services.AddMemoryCache();

        // execution
        //services.AddExecutionModule();
        //services.AddExecutionPipelines();

        // modules infrastructure
        services.AddObservabilityInfrastructure(configuration);
        services.AddUsersInfrastructure(configuration);
        services.AddPeersInfrastructure(configuration);
        services.AddServersInfrastructure(configuration);
        services.AddSubscriptionsInfrastructure(configuration);
        services.AddIdempotencyInfrastructure(configuration);
        services.AddTariffsInfrastructure(configuration);
        services.AddSingleton<IInstanceIdProvider, InstanceIdProvider>();
        

        // host-specific module services
        services.AddObservabilityUserHost();
        services.AddUsersUserHost();
        services.AddPeersUserHost();
        services.AddServersUserHost();
        services.AddSubscriptionsUserHost();
        services.AddTariffsUserHost();

        // pipelines
        services.AddUserHostPipelines();
        services.AddIdempotencyPipeline();

        // workers
        services.AddPeersWorkersUserHost();

        return services;
    }
}