<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" />
        <PackageReference Include="Microsoft.Extensions.Hosting" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Scrutor" />
        <PackageReference Include="Telegram.Bot" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json" CopyToOutputDirectory="Always" />
    </ItemGroup>

</Project>