using DrakkarVpn.Core.Api.Modules.Orchestrator.Application.Options;

namespace DrakkarVpn.Core.Api.Modules.Orchestrator.Infrastructure.Extensions;

public static class OptionsRegistrationExtensions
{
    public static IServiceCollection AddAutoGeneratedLinks(this IServiceCollection services, IConfiguration configuration)
    {
        services.Configure<VpnLinkOptions>(configuration.GetSection("VpnLink"));
        return services;
    }
}