server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: user-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: drakkar
          service: user-api
          __path__: /var/log/drakkar/user-api*.log

  - job_name: admin-api-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: drakkar
          service: admin-api
          __path__: /var/log/drakkar/admin-api*.log