// <auto-generated />
using System;
using DrakkarVpn.Users.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrakkarVpn.Users.Infrastructure.EF.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260309165225_InitialUsers")]
    partial class InitialUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Users.Domain.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BanReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ban_reason");

                    b.Property<DateTime?>("BannedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at_utc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<DateTime?>("ModerationUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("moderation_updated_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_id");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IsInternal")
                        .HasDatabaseName("ix_users_is_internal");

                    b.HasIndex("TelegramId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_telegram_id");

                    b.HasIndex("CreatedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_users_createdat_desc_id_desc");

                    b.HasIndex("ModerationUpdatedAtUtc", "Status")
                        .HasDatabaseName("ix_users_moderation_marker_status");

                    b.HasIndex("Status", "CreatedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_users_status_createdat_desc_id_desc");

                    b.ToTable("app_users", "users");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Users.Domain.Device", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("platform");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeviceId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_devices_subscription");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_devices_sub_createdat_desc");

                    b.HasIndex("UserId", "DeviceId")
                        .HasDatabaseName("ix_devices_sub_deviceid");

                    b.HasIndex("UserId", "StatusUpdatedAtUtc")
                        .HasDatabaseName("ix_devices_user_statusupdatedat");

                    b.ToTable("devices", "users");
                });

            modelBuilder.Entity("DrakkarVpn.Users.Infrastructure.EF.Entity.UserRealtimeStats", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("DeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("device_count");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<bool>("IsSubscriptionActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_subscription_active");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_utc");

                    b.Property<int?>("LastSubscriptionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("last_subscription_status");

                    b.Property<DateTime?>("SubscriptionEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_end_utc");

                    b.Property<int>("SubscriptionMaxDevices")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_max_devices");

                    b.Property<long>("Traffic24hBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("traffic_24h_bytes");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("UserId");

                    b.HasIndex("IsOnline")
                        .HasDatabaseName("idx_userstats_is_online");

                    b.HasIndex("IsSubscriptionActive")
                        .HasDatabaseName("idx_userstats_sub_active");

                    b.HasIndex("LastSeenUtc")
                        .HasDatabaseName("idx_userstats_lastseen");

                    b.HasIndex("SubscriptionEndUtc")
                        .HasDatabaseName("idx_userstats_sub_end");

                    b.HasIndex("Traffic24hBytes")
                        .HasDatabaseName("idx_userstats_traffic24h");

                    b.ToTable("user_realtime_stats", "users");
                });

            modelBuilder.Entity("DrakkarVpn.Core.Api.Modules.Users.Domain.Device", b =>
                {
                    b.HasOne("DrakkarVpn.Core.Api.Modules.Users.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
